database:
  engine: "sqlite:///handoff.db"
  echo: false
  pool_type: QueuePool
handoff:
  buffer: /data/buffer
  holding: /data/holding
endpoint:
  user: jdoe
  host: example.edu
  buffer: /data/buffer
  staging: /data/staging
  commands:
    remote: "ssh {user}@{host} \"{command}\""
    transfer: "bbcp {file} {user}@{host}:{dest}"
logging:
  format: "%(asctime)s:%(name)s:%(levelname)s:%(message)s"
  file: null
  level: INFO
general:
  chunk_size: 1
  timeout: null
  num_threads: 1
  expiration_time: 86400
  pause: 1
